server:
  port: 8087

spring:
  datasource:
    username: root
    password: blogo
    url: jdbc:mysql://132.232.69.133:3306/message?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
#  main:
#    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.example.entity


#showSql
logging:
  level:
    com:
      example:
        mapper : debug